import { LeaderboardTab } from '@/types/leaderboard';

export const LEADERBOARD_TABS: LeaderboardTab[] = [
  { id: "all", label: "All" },
  { id: "5k", label: "$5k" },
  { id: "10k", label: "$10k" },
  { id: "25k", label: "$25k" },
  { id: "50k", label: "$50k" },
  { id: "100k", label: "$100k" },
  { id: "500k", label: "$500k" },
  { id: "1m", label: "$1M" },
] as const;

// Country flag mapping for common countries
export const COUNTRY_FLAG_MAP: Record<string, string> = {
  'usa': 'US',
  'united states': 'US',
  'united states of america': 'US',
  'canada': 'CA',
  'united kingdom': 'GB',
  'uk': 'GB',
  'germany': 'DE',
  'france': 'FR',
  'spain': 'ES',
  'italy': 'IT',
  'netherlands': 'NL',
  'australia': 'AU',
  'japan': 'JP',
  'china': 'CN',
  'india': 'IN',
  'brazil': 'BR',
  'mexico': 'MX',
  'russia': 'RU',
  'south korea': 'KR',
  'singapore': 'SG',
  'switzerland': 'CH',
  'sweden': 'SE',
  'norway': 'NO',
  'denmark': 'DK',
  'finland': 'FI',
  'poland': 'PL',
  'czech republic': 'CZ',
  'hungary': 'HU',
  'romania': 'RO',
  'bulgaria': 'BG',
  'greece': 'GR',
  'turkey': 'TR',
  'israel': 'IL',
  'south africa': 'ZA',
  'egypt': 'EG',
  'nigeria': 'NG',
  'kenya': 'KE',
  'morocco': 'MA',
  'argentina': 'AR',
  'chile': 'CL',
  'colombia': 'CO',
  'peru': 'PE',
  'venezuela': 'VE',
  'thailand': 'TH',
  'vietnam': 'VN',
  'indonesia': 'ID',
  'malaysia': 'MY',
  'philippines': 'PH',
  'new zealand': 'NZ',
  'ireland': 'IE',
  'portugal': 'PT',
  'belgium': 'BE',
  'austria': 'AT',
  'luxembourg': 'LU',
  'iceland': 'IS',
  'estonia': 'EE',
  'latvia': 'LV',
  'lithuania': 'LT',
  'slovakia': 'SK',
  'slovenia': 'SI',
  'croatia': 'HR',
  'serbia': 'RS',
  'bosnia and herzegovina': 'BA',
  'montenegro': 'ME',
  'albania': 'AL',
  'north macedonia': 'MK',
  'moldova': 'MD',
  'ukraine': 'UA',
  'belarus': 'BY',
  'georgia': 'GE',
  'armenia': 'AM',
  'azerbaijan': 'AZ',
  'kazakhstan': 'KZ',
  'uzbekistan': 'UZ',
  'kyrgyzstan': 'KG',
  'tajikistan': 'TJ',
  'turkmenistan': 'TM',
  'afghanistan': 'AF',
  'pakistan': 'PK',
  'bangladesh': 'BD',
  'sri lanka': 'LK',
  'nepal': 'NP',
  'bhutan': 'BT',
  'maldives': 'MV',
  'myanmar': 'MM',
  'cambodia': 'KH',
  'laos': 'LA',
  'brunei': 'BN',
  'mongolia': 'MN',
  'north korea': 'KP',
  'taiwan': 'TW',
  'hong kong': 'HK',
  'macau': 'MO',
  'saudi arabia': 'SA',
  'united arab emirates': 'AE',
  'qatar': 'QA',
  'kuwait': 'KW',
  'bahrain': 'BH',
  'oman': 'OM',
  'yemen': 'YE',
  'iraq': 'IQ',
  'iran': 'IR',
  'syria': 'SY',
  'lebanon': 'LB',
  'jordan': 'JO',
  'palestine': 'PS',
  'cyprus': 'CY',
  'malta': 'MT',
  'monaco': 'MC',
  'liechtenstein': 'LI',
  'andorra': 'AD',
  'san marino': 'SM',
  'vatican city': 'VA',
  'cuba': 'CU',
  'jamaica': 'JM',
  'haiti': 'HT',
  'dominican republic': 'DO',
  'puerto rico': 'PR',
  'costa rica': 'CR',
  'panama': 'PA',
  'nicaragua': 'NI',
  'honduras': 'HN',
  'el salvador': 'SV',
  'guatemala': 'GT',
  'belize': 'BZ',
  'ecuador': 'EC',
  'bolivia': 'BO',
  'paraguay': 'PY',
  'uruguay': 'UY',
  'guyana': 'GY',
  'suriname': 'SR',
  'french guiana': 'GF',
  'falkland islands': 'FK',
  'south georgia and the south sandwich islands': 'GS',
  'antarctica': 'AQ',
  'greenland': 'GL',
  'faroe islands': 'FO',
  'svalbard and jan mayen': 'SJ',
  'bouvet island': 'BV',
  'heard island and mcdonald islands': 'HM',
  'british indian ocean territory': 'IO',
  'christmas island': 'CX',
  'cocos islands': 'CC',
  'norfolk island': 'NF',
  'pitcairn islands': 'PN',
  'south sandwich islands': 'GS',
  'south georgia': 'GS',
  'tristan da cunha': 'SH',
  'saint helena': 'SH',
  'ascension island': 'AC',
  'saint pierre and miquelon': 'PM',
  'saint barthelemy': 'BL',
  'saint martin': 'MF',
  'sint maarten': 'SX',
  'anguilla': 'AI',
  'antigua and barbuda': 'AG',
  'aruba': 'AW',
  'barbados': 'BB',
  'bermuda': 'BM',
  'british virgin islands': 'VG',
  'cayman islands': 'KY',
  'curaçao': 'CW',
  'dominica': 'DM',
  'grenada': 'GD',
  'guadeloupe': 'GP',
  'martinique': 'MQ',
  'montserrat': 'MS',
  'saint kitts and nevis': 'KN',
  'saint lucia': 'LC',
  'saint vincent and the grenadines': 'VC',
  'trinidad and tobago': 'TT',
  'turks and caicos islands': 'TC',
  'us virgin islands': 'VI',
  'american samoa': 'AS',
  'cook islands': 'CK',
  'fiji': 'FJ',
  'french polynesia': 'PF',
  'guam': 'GU',
  'kiribati': 'KI',
  'marshall islands': 'MH',
  'micronesia': 'FM',
  'nauru': 'NR',
  'new caledonia': 'NC',
  'niue': 'NU',
  'northern mariana islands': 'MP',
  'palau': 'PW',
  'papua new guinea': 'PG',
  'samoa': 'WS',
  'solomon islands': 'SB',
  'tokelau': 'TK',
  'tonga': 'TO',
  'tuvalu': 'TV',
  'vanuatu': 'VU',
  'wallis and futuna': 'WF',
};
